services:
  controller:
    container_name: controller
    build:
      dockerfile: ./Docker-controller
    volumes:
      - ./playbooks:/ansible-playbooks
  worker1:
    container_name: worker1
    build:
      dockerfile: ./Docker-worker

  worker2:
    container_name: worker2
    build:
      dockerfile: ./Docker-worker
